server:
  port: 8761
  
eureka:
 instance:
    hostname: "{HOSTNAME:localhost}.eureka"
 client:
    register-with-eureka: false 
    fetch-registry: false
    
#---

#eureka:
#      client:
#        registerWithEureka: true
#        fetchRegistry: true
#        registryFetchIntervalSeconds: 5
#        serviceUrl:
#          defaultZone: http://localhost:8761/eureka
#      instance:
#        preferIpAddress: true